<?php
$ASSETS_LOCATION='/assets/';
$IMAGES_LOCATION=$ASSETS_LOCATION.'images/';
$DOWNLOAD_PDF_LOCATION=$ASSETS_LOCATION.'custom/download_pdf/';
$DEFAULT_IMAGES_LOCATION=$IMAGES_LOCATION.'default_images/';
$PROFILE_LOCATION=$IMAGES_LOCATION.'profile/';

return array(
    'ASSETS_LOCATION'=>$ASSETS_LOCATION,
    'DATE_FORMATE'=>'d-M-Y',
    'MONTH_FORMATE'=>'M-Y',
    'DATEPICKER_DATE_FORMATE'=>'dd-M-yyyy',
    'DATE_FORMATE_WITH_TIME'=>'d-M-Y h:i:s',
    'IMAGES_LOCATION'=>$IMAGES_LOCATION,
    'DOWNLOAD_PDF_LOCATION'=>$DOWNLOAD_PDF_LOCATION,
    'DEFAULT_IMAGES_LOCATION'=>$DEFAULT_IMAGES_LOCATION,
    'PROFILE_LOCATION'=>$PROFILE_LOCATION
);